
# This is your Supabase project configuration

project_id = "tzxxldvukpfyrvwqxbqf"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323
# External URL to use in place of localhost. For use with Gitpod, etc.
# base_url = "https://something.gitpod.io"

# Email testing server. Emails sent with the local dev setup are not actually delivered to emails,
# but instead available to view in the Inbucket web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# List of URLs that can be used as redirects for OAuth signup/login.
additional_redirect_urls = ["https://19337df0-5e18-44d6-b126-85f93158e6e5.lovableproject.com"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be automatically signed up when an invitation is accepted.
enable_confirmations = false

# Configure Supabase Edge Functions
[functions]
[functions.send-teacher-email]
verify_jwt = false
[functions.cleanup-rejected-documents]
verify_jwt = false

# Configure Supabase CLI features
[features]
# Enable DB Diff feature on top of OpenAPI.
db_diff = true
